PREFIX db: <http://mappings.dbpedia.org/server/ontology/classes/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX gn: <http://www.geonames.org/ontology#>
PREFIX dbo: <http://dbpedia.org/page/>

insert {
 ?year dbo:Gross_domestic_product ?GDP
}
where { 
    ?GDP a db:GrossDomesticProductPerCapita .
    ?GDP rdfs:value ?GDP_val .
    ?GDP gn:countryCode ?country_GDP .
    ?GDP db:Year ?GDP_year .

    ?year a db:Year .
    ?year gn:countryCode ?year_country .
    ?year rdfs:label ?year_val .

    FILTER(?GDP_year=?year_val)   
    FILTER(?country_GDP=?year_country) 
} 
