PREFIX db: <http://mappings.dbpedia.org/server/ontology/classes/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX ncit: <https://ncim.nci.nih.gov/ncimbrowser/ConceptReport.jsp?dictionary=NCI%20Metathesaurus&type=synonym&code=>
PREFIX gn: <http://www.geonames.org/ontology#>
PREFIX dbo: <http://dbpedia.org/page/>

INSERT 
{
 ?year dbo:Unemployment ?unemployment
}

WHERE 
{   
    ?unemployment a ncit:C0041674 .
    ?unemployment rdfs:value ?unemployment_val .
    ?unemployment gn:countryCode ?country_unemployment .
    ?unemployment db:Year ?unemployment_year .
    
    ?year a db:Year .
    ?year gn:countryCode ?year_country .
    ?year rdfs:label ?year_val .

    FILTER(?unemployment_year=?year_val)   
    FILTER(?country_unemployment=?year_country) 
} 