PREFIX db: <http://mappings.dbpedia.org/server/ontology/classes/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX econ: <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#> 
PREFIX wd: <http://worldbank.org/> 

INSERT 
{
 ?year econ:unemployment ?unemployment
}

WHERE 
{   
    ?unemployment a econ:C0041674 .
    ?unemployment rdfs:value ?unemployment_val .
    ?unemployment db:Country ?country_unemployment .
    ?unemployment db:Year ?unemployment_year .
    
    ?year a db:Year .
    ?year db:Country ?year_country .
    ?year wd:Year ?year_val .

    FILTER(?unemployment_year=?year_val)   
    FILTER(?country_unemployment=?year_country) 
} 